# Generated by Django 5.2.8 on 2025-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Work", "Work"),
                    ("Personal", "Personal"),
                    ("Shopping", "Shopping"),
                    ("Health", "Health"),
                    ("Education", "Education"),
                ],
                default="General",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
